### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by subproc** [tasket/Qubes-VM-hardening#26]
hi, not sure if this is an issue or not, but when i install qubes-vm-hardening i can't choose between vm-boot-protect or vm-boot-protect-root.
There something i've to type in terminal to choose or the installer have to ask what i want?
sorry if this is the wrong place for questions

**Comment by tasket** [comment]
The qubes-users list is probably the best place to ask questions, and you can cc my tasket@posteo.net address. But its not a big deal since I don't have a lot of issues.

A: There's no choice at install time. The choice is made when you configure your VMs: the service name you add to the Services tab is how it will behave at VM startup (and this allows you to easily change the behavior later on).
